import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";
import React from "react";
export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};
const layout = ({ children }) => {
  return (
    <div>
      <Navbar />
      {children}
      <Footer />
    </div>
  );
};

export default layout;
